import React from 'react';
import { Link } from 'react-router-dom';
import Citation from '../components/Citation/Citation';
import Footer from '../components/Footer/Footer';
import { researchCitations, technicalSpecs } from '../data/research';
import './TechnologyPage.css';

function AcousticLevitation() {
  return (
    <>
      <header className="technology-hero">
        <div className="container">
          <Link to="/" className="back-link">← Back to Home</Link>
          <h1>3D Acoustic Levitation</h1>
          <p className="technology-subtitle">
            Developing precise 3D particle control through acoustic hologram technology
          </p>
        </div>
      </header>

      <main className="technology-content">
        <div className="container">
          <section className="technology-section">
            <h2>Our Vision</h2>
            <p>
              We're developing acoustic hologram-based systems for precise 3D manipulation of particles, 
              gel beads, and living cells. Our goal is to create systems that use multiple interacting 
              pressure fields generated by phased array transducers, enabling simultaneous control of 
              multiple objects in arbitrary 3D configurations with independent positioning.
            </p>
            <p>
              The technology we're building will create precise acoustic pressure fields capable of 
              trapping and manipulating objects from nanometers to millimeters in size—all without 
              physical contact. This represents a fundamental shift toward programmable matter systems 
              where materials can be precisely organized in three-dimensional space.
            </p>
          </section>

          <section className="technology-section">
            <h2>The Science Behind It</h2>
            <p>
              Acoustic holograms are generated using phased array transducers that create complex 3D 
              pressure field patterns. When multiple acoustic waves interfere, they form pressure nodes 
              and antinodes—regions where particles can be trapped and manipulated. By dynamically 
              adjusting the phase and amplitude of individual transducers, these pressure fields can be 
              shaped and moved in real-time.
            </p>
            <p>
              Research by <Citation id={2} /> demonstrates that multiple acoustic holograms can create 
              precise 3D pressure fields for touchless manipulation. The study shows that this approach 
              enables manipulation of solid particles, gel beads, and living cells simultaneously, with 
              each object independently controlled in three-dimensional space.
            </p>
            <p>
              The acoustic fields are gentle, non-toxic, and maintain sterility—making them ideal for 
              biological applications where contactless manipulation is critical. Unlike optical methods, 
              acoustic manipulation works through optically opaque materials, opening possibilities for 
              in-material fabrication and deep-tissue applications.
            </p>
          </section>

          <section className="technology-section">
            <h2>Target Capabilities</h2>
            <p>
              Based on current research and our development roadmap, we're working toward systems with 
              the following capabilities:
            </p>
            <ul className="capabilities-list">
              <li><strong>Multi-object manipulation:</strong> Simultaneous control of multiple particles with independent 3D positioning</li>
              <li><strong>Broad size range:</strong> Manipulation from {technicalSpecs.particleSizeRange}—spanning from nanoparticles to macroscopic objects</li>
              <li><strong>High precision:</strong> {technicalSpecs.positioningPrecision} positioning accuracy for precise spatial control</li>
              <li><strong>Biological compatibility:</strong> Non-contact, sterile operation that maintains cell viability</li>
              <li><strong>Material versatility:</strong> Works with particles, gel beads, living cells, and various biomaterials</li>
              <li><strong>Frequency range:</strong> {technicalSpecs.frequencyRange} for optimal manipulation across different scales</li>
            </ul>
          </section>

          <section className="technology-section">
            <h2>Research Foundation</h2>
            <p>
              Our development is grounded in peer-reviewed research that demonstrates the feasibility 
              and potential of acoustic hologram-based manipulation. The foundational work by Melde et al. 
              <Citation id={2} /> at the Max Planck Institute for Medical Research and Heidelberg University 
              demonstrates that touchless 3D printing using acoustic holograms is not only possible but offers 
              unique advantages over traditional methods.
            </p>
            <p>
              Key findings from this research include:
            </p>
            <ul className="capabilities-list">
              <li>Multiple acoustic holograms can create precise, independently controllable 3D pressure fields</li>
              <li>The technique enables manipulation of diverse materials—from solid particles to living cells</li>
              <li>Acoustic manipulation is non-contact, gentle, and non-toxic to cells</li>
              <li>Sterility is maintained throughout the process, critical for biological applications</li>
            </ul>
            <p>
              We're building on this research to develop commercial systems that translate these 
              laboratory demonstrations into practical programmable matter technologies.
            </p>
          </section>

          <section className="technology-section">
            <h2>Potential Applications</h2>
            <p>
              The applications we're exploring span multiple domains where precise, contactless 
              manipulation offers significant advantages:
            </p>
            <ul className="applications-list">
              <li><strong>Volumetric 3D printing:</strong> Layerless fabrication of complex structures throughout material volumes</li>
              <li><strong>Cell patterning and tissue engineering:</strong> Precise spatial organization of cells for organoid formation and regenerative medicine</li>
              <li><strong>Precision material assembly:</strong> Contactless assembly of micro- and nano-scale components</li>
              <li><strong>Drug delivery systems:</strong> Precise positioning and release of therapeutic particles</li>
              <li><strong>Biomedical research:</strong> Gentle manipulation of cells and biomaterials for experimental studies</li>
            </ul>
          </section>

          <section className="technology-section">
            <h2>Development Roadmap</h2>
            <p>
              As a startup in active research and development, we're working to translate the promising 
              research in acoustic holography into practical systems. Our development focuses on:
            </p>
            <ul className="capabilities-list">
              <li>Advancing phased array transducer technology for more complex pressure field generation</li>
              <li>Developing algorithms for real-time control of multiple independent objects</li>
              <li>Optimizing systems for specific applications in manufacturing and synthetic biology</li>
              <li>Scaling from laboratory demonstrations to commercial-grade systems</li>
            </ul>
            <p>
              We're actively seeking research collaborations and partnerships to accelerate development 
              and explore new applications for acoustic hologram-based manipulation.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </>
  );
}

export default AcousticLevitation;

